#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d I II III IV 

bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#borders 
bspc config border_width         2
bspc config focus_follows_pointer true

#window rule
bspc rule -a Zathura state=tiled

#default execs
$HOME/.config/polybar/launch.sh
xsetroot -cursor_name left_ptr &
picom --experimental-backend &
bash ~/.config/polybar/launch.sh --blocks
